version: '3.9'

services:
  php-web:
    image: php:8.1-apache
    container_name: php-resto
    restart: always
    ports:
      - "86:80"
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./logs/php:/var/log/php  # Sinkronisasi log PHP
      - ./logs/apache:/var/log/apache2
    depends_on:
      php-mysql:
        condition: service_healthy
      loki:
        condition: service_started
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: debug

  php-mysql:
    image: mysql:5.7
    container_name: php-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: restaurantdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./restaurantDB.txt:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    user: "0:0"
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki  # Menggunakan volume untuk penyimpanan Loki
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./logs/apache:/var/log/apache2
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network
    entrypoint: ["/bin/sh", "-c", "mkdir -p /loki /loki/boltdb-shipper-index /loki/chunks /var/loki/compactor && chmod -R 777 /loki /var/loki/compactor && /usr/bin/loki -config.file=/etc/loki/local-config.yaml"]


  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    restart: always
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./logs/php:/var/log/php
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
  grafana_data:
  loki_data:  # Volume baru untuk Loki
