server:
  http_listen_port: 9080
  grpc_listen_port: 37337

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  - job_name: "php"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "php"
          __path__: /var/log/php/*.log

  - job_name: "apache"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "apache"
          __path__: /var/log/apache2/*.log

