apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-mysql-resto
  namespace: preprod
  labels:
    app: php-mysql-resto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-mysql-resto
  template:
    metadata:
      labels:
        app: php-mysql-resto
    spec:
      containers:
        - name: php-mysql-resto
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: restaurantdb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-resto-pvc
        - name: db-init
          configMap:
            name: db-init-sql-resto
