apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preprod
resources:
  - web/deployment.yaml
  - web/service.yaml
  - web/hpa.yaml
  - db/deployment.yaml
  - db/service.yaml
  - db/pvc.yaml
  - db/hpa.yaml
