name: Deploy to Biznet Gio VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.BIZNET_GIO_HOST }}
        username: ${{ secrets.BIZNET_GIO_USER }}
        key: ${{ secrets.BIZNET_GIO_SSH_KEY }}
        port: ${{ secrets.BIZNET_GIO_PORT }}
        script: |
            cd /home/DevOps/project/resto/
            git reset --hard
            git pull origin main
            
            # Cek perubahan pada file docker-compose
            changed_files=$(git diff --name-only HEAD~1 HEAD | grep 'docker-compose' || echo "")

            if [ -n "$changed_files" ]; then
              changed_services=$(echo "$changed_files" | xargs -r docker-compose config --services)
            else
              changed_services=""
            fi

            monitoring_services=("grafana" "promtail" "loki")
            monitoring_changes=false

            if [ -n "$changed_services" ]; then
              for service in $changed_services; do
                if [[ " ${monitoring_services[@]} " =~ " ${service} " ]]; then
                  monitoring_changes=true
                else
                  echo "Updating service: $service"
                  docker-compose stop $service
                  docker-compose rm -f $service
                  docker-compose up -d $service
                fi
              done
            fi

            if [ "$monitoring_changes" = true ]; then
              echo "Restarting monitoring services (Grafana, Promtail, Loki)"
              docker-compose restart grafana promtail loki
            fi

            docker-compose ps
