name: Deploy to Biznet Gio VPS

on:
  push:
    branches:
      - main  # bisa ganti branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.BIZNET_GIO_HOST }}
        username: ${{ secrets.BIZNET_GIO_USER }}
        key: ${{ secrets.BIZNET_GIO_SSH_KEY }}
        port: ${{ secrets.BIZNET_GIO_PORT }}
        script: |
            # Hentikan dan hapus container lama jika ada
            docker stop restaurant-app || true
            docker rm restaurant-app || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest

            docker run -d --name restaurant-app -p 83:80 --restart always ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest

            docker exec restaurant-app chmod -R 755 /usr/share/nginx/html
