name: Deploy to Biznet Gio VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.BIZNET_GIO_HOST }}
        username: ${{ secrets.BIZNET_GIO_USER }}
        key: ${{ secrets.BIZNET_GIO_SSH_KEY }}
        port: ${{ secrets.BIZNET_GIO_PORT }}
        script: |
            cd /home/DevOps/project/resto/
            git reset --hard
            git pull origin main
            
            docker-compose down --remove-orphans
            docker system prune -af --volumes

            docker pull ${{ secrets.DOCKER_USERNAME }}/restaurant-app:latest
            
            docker-compose up -d --force-recreate
            docker-compose ps
