apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-web-resto
  namespace: preprod
  labels:
    app: php-web-resto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-web-resto
  template:
    metadata:
      labels:
        app: php-web-resto
    spec:
      containers:
        - name: php-web-resto
          image: resto-web:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: php-log
              mountPath: /var/log/php
            - name: apache-log
              mountPath: /var/log/apache2
            - name: php-ini
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
      volumes:
        - name: php-log
          emptyDir: {}
        - name: apache-log
          emptyDir: {}
        - name: php-ini
          configMap:
            name: php-ini
