apiVersion: v1
kind: Service
metadata:
  name: php-web-resto
  namespace: preprod
spec:
  selector:
    app: php-web-resto
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30086
